@BloodDonationPlatform.API_HostAddress = https://localhost:7021

### Get all hospitals
GET {{BloodDonationPlatform.API_HostAddress}}/api/hospital/
Accept: application/json

### Get all hospitals by-name
GET {{BloodDonationPlatform.API_HostAddress}}/api/hospital/get-all-by-name
Accept: application/json

### Get hospital by ID
GET {{BloodDonationPlatform.API_HostAddress}}/api/hospital/43
Accept: application/json

### Create a new hospital
POST {{BloodDonationPlatform.API_HostAddress}}/api/hospital/
Content-Type: application/json
{
  "name": "khalid hospital",
  "phoneNumber": "01065464542",
  "areaId": 3,
  "minimumBloodQuantityByLiter": 9,
  "createdById": 1
}

### Update existing hospital
PUT {{BloodDonationPlatform.API_HostAddress}}/api/hospital/45
Content-Type: application/json
{
  "name": "khalid hospital",
  "phoneNumber": "01065464542",
  "areaId": 3,
  "minimumBloodQuantityByLiter": 4
}

### Delete hospital
DELETE {{BloodDonationPlatform.API_HostAddress}}/api/hospital/45
Accept: application/json
